name: Validate HACS

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
      - name: HACS validation
        uses: hacs/action@main
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
        with:
          category: theme
